// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATRw5zePIdOiV603oPB4KbZwWmjF_TN7M',
    appId: '1:423888618447:web:2c6560d7b06deb2ebcc8ba',
    messagingSenderId: '423888618447',
    projectId: 'cw-6-1dc81',
    authDomain: 'cw-6-1dc81.firebaseapp.com',
    storageBucket: 'cw-6-1dc81.appspot.com',
    measurementId: 'G-SE8G49S4ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPXDofYnMTOzgN49Pj_nng4QfUP-D7HHU',
    appId: '1:423888618447:android:f784589289cfe19bbcc8ba',
    messagingSenderId: '423888618447',
    projectId: 'cw-6-1dc81',
    storageBucket: 'cw-6-1dc81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYdGBHzk6PpGN-u7OcO36d1cSsdl4zBYU',
    appId: '1:423888618447:ios:bb95ccd2081a8b01bcc8ba',
    messagingSenderId: '423888618447',
    projectId: 'cw-6-1dc81',
    storageBucket: 'cw-6-1dc81.appspot.com',
    iosBundleId: 'com.example.cw06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYdGBHzk6PpGN-u7OcO36d1cSsdl4zBYU',
    appId: '1:423888618447:ios:192a4f2ae3911a9bbcc8ba',
    messagingSenderId: '423888618447',
    projectId: 'cw-6-1dc81',
    storageBucket: 'cw-6-1dc81.appspot.com',
    iosBundleId: 'com.example.cw06.RunnerTests',
  );
}
